{"frames":[{"func":"tract_data_1 %>% cbind(st_centroid(.) %>% st_coordinates %>% \n    as.data.frame()) %>% as.data.frame()","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"as.data.frame(.)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"cbind(., st_centroid(.) %>% st_coordinates %>% as.data.frame())","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":".handleSimpleError(function (cond) \n.Internal(C_tryCatchHelper(addr, 1L, cond)), \"object 'tract_data_1' not found\", \n    base::quote(NULL))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"h(simpleError(msg, call))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in h(simpleError(msg, call)) : \n  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': object 'tract_data_1' not found\n"}